CREATE TABLE CHATMESSAGE(
    CHATTINGMESSAGE_ID INT PRIMARY KEY,
    UNAME1 INT,
    UNAME2 INT,
    CONTENT VARCHAR(4000),
    REGDATE DATE NOT NULL,
    
    CONSTRAINT FK_CHATMESSAGE_UNAME1 FOREIGN KEY (UNAME1) REFERENCES MEMBER(ID),
    CONSTRAINT FK_CHATMESSAGE_UNAME2 FOREIGN KEY (UNAME2) REFERENCES MEMBER(ID)
);


CREATE SEQUENCE CHATMESSAGE_ID START WITH 1 INCREMENT BY 1 MAXVALUE 999 CYCLE NOCACHE;