CREATE TABLE CHATTINGROOM (
    CHATTINGROOM_ID INT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL
);

CREATE SEQUENCE CHATTINGROOM_ID START WITH 1 INCREMENT BY 1 MAXVALUE 999 CYCLE NOCACHE;

INSERT INTO chattingroom (chattingroom_id , NAME)
VALUES (CHATTINGROOM_ID.NEXTVAL,'응가방');

COMMIT;