-- 유저 테이블 생성

CREATE TABLE MEMBER (
    ID VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    NICKNAME VARCHAR2(50) NOT NULL,
    PW VARCHAR2(50) NOT NULL
);

INSERT INTO MEMBER (ID, NAME, NICKNAME, PW)
VALUES ('YEOUN', '연창현','뿌직','1234');

INSERT INTO MEMBER (ID, NAME, NICKNAME, PW)
VALUES ('JIYUN', '김지윤','뿌웅','1234');